name: Pipeline de Testes da Calculadora

on:
  push:
    branches: [ "main" ]

jobs:
  testes-calculadora:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar o Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar o pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Executar os testes de soma
        run: |
          pytest tests/test_soma.py 

    test_sub:
        needs: testes-calculadora
    test:_nuh:
    test_div:
    deploy:
