name: Pipeline de Teste

on:
  push:
    branches: [ "main" ]

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar Código de Repositório 
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar Dependencias do Node e Python
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          # Se você não usa Node (npm), comente ou apague as duas linhas abaixo:
          npm install || echo "Sem package.json para instalar"

      - name: Executar testes Python
        run: pytest || echo "Nenhum teste em Python criado ainda"

      - name: Executar testes Node
        run: npm test || echo "Nenhum teste em Node criado ainda"

  deploy:
    needs: teste
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy realizado com sucesso!"
